sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - vendor/assets/bower_components
rvm:
- 2.2.0
addons:
  postgresql: '9.3'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
- bundle exec teaspoon